-- PouchBase core schema entrypoint.
--
-- The canonical schema now lives in:
-- supabase/migrations/20260425173000_core_schema.sql
--
-- Apply that migration through Supabase migrations or paste its contents into
-- the Supabase SQL editor for a clean foundation reset.
